import os

MODEL_PATH = os.getenv("MODEL_PATH", "models/qwen2.5-coder-14b-instruct-q5_k_m.gguf")
MODEL_N_CTX = int(os.getenv("MODEL_N_CTX", "8192"))
MODEL_N_THREADS = int(os.getenv("MODEL_N_THREADS", "2"))
TEMPERATURE = float(os.getenv("TEMPERATURE", "0.7"))
MAX_TOKENS = int(os.getenv("MAX_TOKENS", "512"))
RESPONSE_MAX_CHARS = int(os.getenv("RESPONSE_MAX_CHARS", "300"))
CONTEXT_SLOT_COUNT = int(os.getenv("CONTEXT_SLOT_COUNT", "10"))
SEARCH_MAX_RESULTS = int(os.getenv("SEARCH_MAX_RESULTS", "5"))
SEARCH_TIMEOUT = int(os.getenv("SEARCH_TIMEOUT", "30"))
BOT_DID = os.getenv("BOT_DID", "")
BOT_HANDLE = os.getenv("BOT_HANDLE", "")
BOT_PASSWORD = os.getenv("BOT_PASSWORD", "")
OWNER_DID = os.getenv("OWNER_DID", "")
PAT = os.getenv("PAT", "")
GITHUB_REPOSITORY = os.getenv("GITHUB_REPOSITORY", "")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY", "")
