import os

MODEL_PATH = "models/qwen2.5-coder-14b-instruct-q5_k_m.gguf"
MODEL_N_CTX = 8192
MODEL_N_THREADS = 2
TEMPERATURE = 0.7
MAX_TOKENS = 512
RESPONSE_MAX_CHARS = 300
CONTEXT_SECRET_COUNT = 10
SEARCH_MAX_RESULTS = 5
SEARCH_TIMEOUT = 30
